
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `TNA`=list(
        `type`="package", 
        `author`="Dylan Girault, Mohammed Saqr, Sonsoles L\u00F3pez-Pernas, Santtu Tikka", 
        `year`=2025, 
        `title`="Transition Network Analysis (TNA)", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=tna", 
        `url`="https://CRAN.R-project.org/package=tna"))
