
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `TNA`=list(
        `type`="package", 
        `author`="Dylan Girault, Mohammed Saqr, Sonsoles L\u00F3pez-Pernas, Santtu Tikka", 
        `year`=2025, 
        `title`="A module for Transition Network Analysis (TNA)", 
        `publisher`="Retrieved from https://doi.org/10.1177/0146621625134884'", 
        `url`="https://doi.org/10.1177/0146621625134884"))
