
# This file is automatically generated, you probably don't want to edit this

TNAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "TNAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            buildModel_variables_long_actor = NULL,
            buildModel_variables_long_time = NULL,
            buildModel_variables_long_action = NULL,
            buildModel_variables_long_order = NULL,
            buildModel_type = "relative",
            buildModel_scaling = "noScaling",
            buildModel_show_matrix = FALSE,
            buildModel_threshold = 900,
            buildModel_show_plot = TRUE,
            buildModel_plot_cut = 0.1,
            buildModel_plot_min_value = 0.05,
            buildModel_plot_edge_label_size = 1,
            buildModel_plot_node_size = 1,
            buildModel_plot_node_label_size = 1,
            buildModel_plot_layout = NULL,
            buildModel_show_histo = FALSE,
            buildModel_show_frequencies = FALSE,
            buildModel_show_mosaic = FALSE,
            buildModel_digits = 1,
            centrality_loops = FALSE,
            centrality_normalize = FALSE,
            centrality_show_table = FALSE,
            centrality_show_plot = FALSE,
            centrality_Betweenness = TRUE,
            centrality_BetweennessRSP = FALSE,
            centrality_Closeness = FALSE,
            centrality_ClosenessIn = FALSE,
            centrality_ClosenessOut = FALSE,
            centrality_Clustering = FALSE,
            centrality_Diffusion = FALSE,
            centrality_InStrength = TRUE,
            centrality_OutStrength = TRUE,
            edgeBetweenness_show_table = FALSE,
            edgeBetweenness_show_plot = FALSE,
            edgeBetweenness_plot_cut = 0.1,
            edgeBetweenness_plot_min_value = 0.05,
            edgeBetweenness_plot_edge_label_size = 1,
            edgeBetweenness_plot_node_size = 1,
            edgeBetweenness_plot_node_label_size = 1,
            edgeBetweenness_plot_layout = NULL,
            community_methods = "spinglass",
            community_gamma = 1,
            community_show_table = FALSE,
            community_show_plot = FALSE,
            cliques_size = 2,
            cliques_threshold = 0,
            cliques_show_text = FALSE,
            cliques_show_plot = FALSE,
            cliques_plot_cut = 0.1,
            cliques_plot_min_value = 0,
            cliques_plot_edge_label_size = 1,
            cliques_plot_node_size = 1,
            cliques_plot_node_label_size = 1,
            cliques_plot_layout = "circle",
            bootstrap_iteration = 1000,
            bootstrap_level = 0.05,
            bootstrap_method = "stability",
            bootstrap_range_low = 0.75,
            bootstrap_range_up = 1.25,
            bootstrap_threshold = 0.1,
            bootstrap_show_plot = FALSE,
            bootstrap_show_table = FALSE,
            bootstrap_plot_cut = 0.1,
            bootstrap_plot_min_value = 0.05,
            bootstrap_plot_edge_label_size = 1,
            bootstrap_plot_node_size = 1,
            bootstrap_plot_node_label_size = 1,
            bootstrap_plot_layout = NULL,
            sequences_type = "index",
            sequences_scale = "proportion",
            sequences_geom = "bar",
            sequences_include_na = TRUE,
            sequences_tick = 5,
            sequences_show_plot = FALSE, ...) {

            super$initialize(
                package="JTNA",
                name="TNA",
                requiresData=TRUE,
                ...)

            private$..buildModel_variables_long_actor <- jmvcore::OptionVariable$new(
                "buildModel_variables_long_actor",
                buildModel_variables_long_actor)
            private$..buildModel_variables_long_time <- jmvcore::OptionVariable$new(
                "buildModel_variables_long_time",
                buildModel_variables_long_time)
            private$..buildModel_variables_long_action <- jmvcore::OptionVariable$new(
                "buildModel_variables_long_action",
                buildModel_variables_long_action)
            private$..buildModel_variables_long_order <- jmvcore::OptionVariable$new(
                "buildModel_variables_long_order",
                buildModel_variables_long_order)
            private$..buildModel_type <- jmvcore::OptionList$new(
                "buildModel_type",
                buildModel_type,
                options=list(
                    "relative",
                    "frequency",
                    "co-occurrence"),
                default="relative")
            private$..buildModel_scaling <- jmvcore::OptionList$new(
                "buildModel_scaling",
                buildModel_scaling,
                options=list(
                    "noScaling",
                    "minmax",
                    "max",
                    "rank"),
                default="noScaling")
            private$..buildModel_show_matrix <- jmvcore::OptionBool$new(
                "buildModel_show_matrix",
                buildModel_show_matrix,
                default=FALSE)
            private$..buildModel_threshold <- jmvcore::OptionInteger$new(
                "buildModel_threshold",
                buildModel_threshold,
                default=900)
            private$..buildModel_show_plot <- jmvcore::OptionBool$new(
                "buildModel_show_plot",
                buildModel_show_plot,
                default=TRUE)
            private$..buildModel_plot_cut <- jmvcore::OptionNumber$new(
                "buildModel_plot_cut",
                buildModel_plot_cut,
                default=0.1,
                min=0,
                max=1)
            private$..buildModel_plot_min_value <- jmvcore::OptionNumber$new(
                "buildModel_plot_min_value",
                buildModel_plot_min_value,
                default=0.05,
                min=0,
                max=1)
            private$..buildModel_plot_edge_label_size <- jmvcore::OptionNumber$new(
                "buildModel_plot_edge_label_size",
                buildModel_plot_edge_label_size,
                default=1,
                min=0,
                max=10)
            private$..buildModel_plot_node_size <- jmvcore::OptionNumber$new(
                "buildModel_plot_node_size",
                buildModel_plot_node_size,
                default=1,
                min=0,
                max=2)
            private$..buildModel_plot_node_label_size <- jmvcore::OptionNumber$new(
                "buildModel_plot_node_label_size",
                buildModel_plot_node_label_size,
                default=1,
                min=0,
                max=10)
            private$..buildModel_plot_layout <- jmvcore::OptionList$new(
                "buildModel_plot_layout",
                buildModel_plot_layout,
                options=list(
                    "circle",
                    "spring"))
            private$..buildModel_show_histo <- jmvcore::OptionBool$new(
                "buildModel_show_histo",
                buildModel_show_histo,
                default=FALSE)
            private$..buildModel_show_frequencies <- jmvcore::OptionBool$new(
                "buildModel_show_frequencies",
                buildModel_show_frequencies,
                default=FALSE)
            private$..buildModel_show_mosaic <- jmvcore::OptionBool$new(
                "buildModel_show_mosaic",
                buildModel_show_mosaic,
                default=FALSE)
            private$..buildModel_digits <- jmvcore::OptionInteger$new(
                "buildModel_digits",
                buildModel_digits,
                default=1)
            private$..centrality_loops <- jmvcore::OptionBool$new(
                "centrality_loops",
                centrality_loops,
                default=FALSE)
            private$..centrality_normalize <- jmvcore::OptionBool$new(
                "centrality_normalize",
                centrality_normalize,
                default=FALSE)
            private$..centrality_show_table <- jmvcore::OptionBool$new(
                "centrality_show_table",
                centrality_show_table,
                default=FALSE)
            private$..centrality_show_plot <- jmvcore::OptionBool$new(
                "centrality_show_plot",
                centrality_show_plot,
                default=FALSE)
            private$..centrality_Betweenness <- jmvcore::OptionBool$new(
                "centrality_Betweenness",
                centrality_Betweenness,
                default=TRUE)
            private$..centrality_BetweennessRSP <- jmvcore::OptionBool$new(
                "centrality_BetweennessRSP",
                centrality_BetweennessRSP,
                default=FALSE)
            private$..centrality_Closeness <- jmvcore::OptionBool$new(
                "centrality_Closeness",
                centrality_Closeness,
                default=FALSE)
            private$..centrality_ClosenessIn <- jmvcore::OptionBool$new(
                "centrality_ClosenessIn",
                centrality_ClosenessIn,
                default=FALSE)
            private$..centrality_ClosenessOut <- jmvcore::OptionBool$new(
                "centrality_ClosenessOut",
                centrality_ClosenessOut,
                default=FALSE)
            private$..centrality_Clustering <- jmvcore::OptionBool$new(
                "centrality_Clustering",
                centrality_Clustering,
                default=FALSE)
            private$..centrality_Diffusion <- jmvcore::OptionBool$new(
                "centrality_Diffusion",
                centrality_Diffusion,
                default=FALSE)
            private$..centrality_InStrength <- jmvcore::OptionBool$new(
                "centrality_InStrength",
                centrality_InStrength,
                default=TRUE)
            private$..centrality_OutStrength <- jmvcore::OptionBool$new(
                "centrality_OutStrength",
                centrality_OutStrength,
                default=TRUE)
            private$..edgeBetweenness_show_table <- jmvcore::OptionBool$new(
                "edgeBetweenness_show_table",
                edgeBetweenness_show_table,
                default=FALSE)
            private$..edgeBetweenness_show_plot <- jmvcore::OptionBool$new(
                "edgeBetweenness_show_plot",
                edgeBetweenness_show_plot,
                default=FALSE)
            private$..edgeBetweenness_plot_cut <- jmvcore::OptionNumber$new(
                "edgeBetweenness_plot_cut",
                edgeBetweenness_plot_cut,
                default=0.1,
                min=0,
                max=1)
            private$..edgeBetweenness_plot_min_value <- jmvcore::OptionNumber$new(
                "edgeBetweenness_plot_min_value",
                edgeBetweenness_plot_min_value,
                default=0.05,
                min=0,
                max=1)
            private$..edgeBetweenness_plot_edge_label_size <- jmvcore::OptionNumber$new(
                "edgeBetweenness_plot_edge_label_size",
                edgeBetweenness_plot_edge_label_size,
                default=1,
                min=0,
                max=10)
            private$..edgeBetweenness_plot_node_size <- jmvcore::OptionNumber$new(
                "edgeBetweenness_plot_node_size",
                edgeBetweenness_plot_node_size,
                default=1,
                min=0,
                max=2)
            private$..edgeBetweenness_plot_node_label_size <- jmvcore::OptionNumber$new(
                "edgeBetweenness_plot_node_label_size",
                edgeBetweenness_plot_node_label_size,
                default=1,
                min=0,
                max=10)
            private$..edgeBetweenness_plot_layout <- jmvcore::OptionList$new(
                "edgeBetweenness_plot_layout",
                edgeBetweenness_plot_layout,
                options=list(
                    "circle",
                    "spring"))
            private$..community_methods <- jmvcore::OptionList$new(
                "community_methods",
                community_methods,
                default="spinglass",
                options=list(
                    "spinglass",
                    "walktrap",
                    "fast_greedy",
                    "label_prop",
                    "infomap",
                    "edge_betweenness",
                    "leading_eigen"))
            private$..community_gamma <- jmvcore::OptionInteger$new(
                "community_gamma",
                community_gamma,
                default=1,
                min=0,
                max=100)
            private$..community_show_table <- jmvcore::OptionBool$new(
                "community_show_table",
                community_show_table,
                default=FALSE)
            private$..community_show_plot <- jmvcore::OptionBool$new(
                "community_show_plot",
                community_show_plot,
                default=FALSE)
            private$..cliques_size <- jmvcore::OptionInteger$new(
                "cliques_size",
                cliques_size,
                default=2,
                min=2,
                max=10)
            private$..cliques_threshold <- jmvcore::OptionNumber$new(
                "cliques_threshold",
                cliques_threshold,
                default=0,
                min=0,
                max=1)
            private$..cliques_show_text <- jmvcore::OptionBool$new(
                "cliques_show_text",
                cliques_show_text,
                default=FALSE)
            private$..cliques_show_plot <- jmvcore::OptionBool$new(
                "cliques_show_plot",
                cliques_show_plot,
                default=FALSE)
            private$..cliques_plot_cut <- jmvcore::OptionNumber$new(
                "cliques_plot_cut",
                cliques_plot_cut,
                default=0.1,
                min=0,
                max=1)
            private$..cliques_plot_min_value <- jmvcore::OptionNumber$new(
                "cliques_plot_min_value",
                cliques_plot_min_value,
                default=0,
                min=0,
                max=1)
            private$..cliques_plot_edge_label_size <- jmvcore::OptionNumber$new(
                "cliques_plot_edge_label_size",
                cliques_plot_edge_label_size,
                default=1,
                min=0,
                max=10)
            private$..cliques_plot_node_size <- jmvcore::OptionNumber$new(
                "cliques_plot_node_size",
                cliques_plot_node_size,
                default=1,
                min=0,
                max=2)
            private$..cliques_plot_node_label_size <- jmvcore::OptionNumber$new(
                "cliques_plot_node_label_size",
                cliques_plot_node_label_size,
                default=1,
                min=0,
                max=10)
            private$..cliques_plot_layout <- jmvcore::OptionList$new(
                "cliques_plot_layout",
                cliques_plot_layout,
                default="circle",
                options=list(
                    "circle",
                    "spring"))
            private$..bootstrap_iteration <- jmvcore::OptionInteger$new(
                "bootstrap_iteration",
                bootstrap_iteration,
                default=1000,
                min=0,
                max=10000)
            private$..bootstrap_level <- jmvcore::OptionNumber$new(
                "bootstrap_level",
                bootstrap_level,
                default=0.05,
                min=0,
                max=1)
            private$..bootstrap_method <- jmvcore::OptionList$new(
                "bootstrap_method",
                bootstrap_method,
                default="stability",
                options=list(
                    "stability",
                    "threshold"))
            private$..bootstrap_range_low <- jmvcore::OptionNumber$new(
                "bootstrap_range_low",
                bootstrap_range_low,
                default=0.75,
                min=0,
                max=10)
            private$..bootstrap_range_up <- jmvcore::OptionNumber$new(
                "bootstrap_range_up",
                bootstrap_range_up,
                default=1.25,
                min=0,
                max=10)
            private$..bootstrap_threshold <- jmvcore::OptionNumber$new(
                "bootstrap_threshold",
                bootstrap_threshold,
                default=0.1,
                min=0,
                max=1)
            private$..bootstrap_show_plot <- jmvcore::OptionBool$new(
                "bootstrap_show_plot",
                bootstrap_show_plot,
                default=FALSE)
            private$..bootstrap_show_table <- jmvcore::OptionBool$new(
                "bootstrap_show_table",
                bootstrap_show_table,
                default=FALSE)
            private$..bootstrap_plot_cut <- jmvcore::OptionNumber$new(
                "bootstrap_plot_cut",
                bootstrap_plot_cut,
                default=0.1,
                min=0,
                max=1)
            private$..bootstrap_plot_min_value <- jmvcore::OptionNumber$new(
                "bootstrap_plot_min_value",
                bootstrap_plot_min_value,
                default=0.05,
                min=0,
                max=1)
            private$..bootstrap_plot_edge_label_size <- jmvcore::OptionNumber$new(
                "bootstrap_plot_edge_label_size",
                bootstrap_plot_edge_label_size,
                default=1,
                min=0,
                max=10)
            private$..bootstrap_plot_node_size <- jmvcore::OptionNumber$new(
                "bootstrap_plot_node_size",
                bootstrap_plot_node_size,
                default=1,
                min=0,
                max=2)
            private$..bootstrap_plot_node_label_size <- jmvcore::OptionNumber$new(
                "bootstrap_plot_node_label_size",
                bootstrap_plot_node_label_size,
                default=1,
                min=0,
                max=10)
            private$..bootstrap_plot_layout <- jmvcore::OptionList$new(
                "bootstrap_plot_layout",
                bootstrap_plot_layout,
                options=list(
                    "circle",
                    "spring"))
            private$..sequences_type <- jmvcore::OptionList$new(
                "sequences_type",
                sequences_type,
                default="index",
                options=list(
                    "index",
                    "distribution"))
            private$..sequences_scale <- jmvcore::OptionList$new(
                "sequences_scale",
                sequences_scale,
                default="proportion",
                options=list(
                    "proportion",
                    "count"))
            private$..sequences_geom <- jmvcore::OptionList$new(
                "sequences_geom",
                sequences_geom,
                default="bar",
                options=list(
                    "bar",
                    "area"))
            private$..sequences_include_na <- jmvcore::OptionBool$new(
                "sequences_include_na",
                sequences_include_na,
                default=TRUE)
            private$..sequences_tick <- jmvcore::OptionInteger$new(
                "sequences_tick",
                sequences_tick,
                default=5,
                min=1,
                max=20)
            private$..sequences_show_plot <- jmvcore::OptionBool$new(
                "sequences_show_plot",
                sequences_show_plot,
                default=FALSE)

            self$.addOption(private$..buildModel_variables_long_actor)
            self$.addOption(private$..buildModel_variables_long_time)
            self$.addOption(private$..buildModel_variables_long_action)
            self$.addOption(private$..buildModel_variables_long_order)
            self$.addOption(private$..buildModel_type)
            self$.addOption(private$..buildModel_scaling)
            self$.addOption(private$..buildModel_show_matrix)
            self$.addOption(private$..buildModel_threshold)
            self$.addOption(private$..buildModel_show_plot)
            self$.addOption(private$..buildModel_plot_cut)
            self$.addOption(private$..buildModel_plot_min_value)
            self$.addOption(private$..buildModel_plot_edge_label_size)
            self$.addOption(private$..buildModel_plot_node_size)
            self$.addOption(private$..buildModel_plot_node_label_size)
            self$.addOption(private$..buildModel_plot_layout)
            self$.addOption(private$..buildModel_show_histo)
            self$.addOption(private$..buildModel_show_frequencies)
            self$.addOption(private$..buildModel_show_mosaic)
            self$.addOption(private$..buildModel_digits)
            self$.addOption(private$..centrality_loops)
            self$.addOption(private$..centrality_normalize)
            self$.addOption(private$..centrality_show_table)
            self$.addOption(private$..centrality_show_plot)
            self$.addOption(private$..centrality_Betweenness)
            self$.addOption(private$..centrality_BetweennessRSP)
            self$.addOption(private$..centrality_Closeness)
            self$.addOption(private$..centrality_ClosenessIn)
            self$.addOption(private$..centrality_ClosenessOut)
            self$.addOption(private$..centrality_Clustering)
            self$.addOption(private$..centrality_Diffusion)
            self$.addOption(private$..centrality_InStrength)
            self$.addOption(private$..centrality_OutStrength)
            self$.addOption(private$..edgeBetweenness_show_table)
            self$.addOption(private$..edgeBetweenness_show_plot)
            self$.addOption(private$..edgeBetweenness_plot_cut)
            self$.addOption(private$..edgeBetweenness_plot_min_value)
            self$.addOption(private$..edgeBetweenness_plot_edge_label_size)
            self$.addOption(private$..edgeBetweenness_plot_node_size)
            self$.addOption(private$..edgeBetweenness_plot_node_label_size)
            self$.addOption(private$..edgeBetweenness_plot_layout)
            self$.addOption(private$..community_methods)
            self$.addOption(private$..community_gamma)
            self$.addOption(private$..community_show_table)
            self$.addOption(private$..community_show_plot)
            self$.addOption(private$..cliques_size)
            self$.addOption(private$..cliques_threshold)
            self$.addOption(private$..cliques_show_text)
            self$.addOption(private$..cliques_show_plot)
            self$.addOption(private$..cliques_plot_cut)
            self$.addOption(private$..cliques_plot_min_value)
            self$.addOption(private$..cliques_plot_edge_label_size)
            self$.addOption(private$..cliques_plot_node_size)
            self$.addOption(private$..cliques_plot_node_label_size)
            self$.addOption(private$..cliques_plot_layout)
            self$.addOption(private$..bootstrap_iteration)
            self$.addOption(private$..bootstrap_level)
            self$.addOption(private$..bootstrap_method)
            self$.addOption(private$..bootstrap_range_low)
            self$.addOption(private$..bootstrap_range_up)
            self$.addOption(private$..bootstrap_threshold)
            self$.addOption(private$..bootstrap_show_plot)
            self$.addOption(private$..bootstrap_show_table)
            self$.addOption(private$..bootstrap_plot_cut)
            self$.addOption(private$..bootstrap_plot_min_value)
            self$.addOption(private$..bootstrap_plot_edge_label_size)
            self$.addOption(private$..bootstrap_plot_node_size)
            self$.addOption(private$..bootstrap_plot_node_label_size)
            self$.addOption(private$..bootstrap_plot_layout)
            self$.addOption(private$..sequences_type)
            self$.addOption(private$..sequences_scale)
            self$.addOption(private$..sequences_geom)
            self$.addOption(private$..sequences_include_na)
            self$.addOption(private$..sequences_tick)
            self$.addOption(private$..sequences_show_plot)
        }),
    active = list(
        buildModel_variables_long_actor = function() private$..buildModel_variables_long_actor$value,
        buildModel_variables_long_time = function() private$..buildModel_variables_long_time$value,
        buildModel_variables_long_action = function() private$..buildModel_variables_long_action$value,
        buildModel_variables_long_order = function() private$..buildModel_variables_long_order$value,
        buildModel_type = function() private$..buildModel_type$value,
        buildModel_scaling = function() private$..buildModel_scaling$value,
        buildModel_show_matrix = function() private$..buildModel_show_matrix$value,
        buildModel_threshold = function() private$..buildModel_threshold$value,
        buildModel_show_plot = function() private$..buildModel_show_plot$value,
        buildModel_plot_cut = function() private$..buildModel_plot_cut$value,
        buildModel_plot_min_value = function() private$..buildModel_plot_min_value$value,
        buildModel_plot_edge_label_size = function() private$..buildModel_plot_edge_label_size$value,
        buildModel_plot_node_size = function() private$..buildModel_plot_node_size$value,
        buildModel_plot_node_label_size = function() private$..buildModel_plot_node_label_size$value,
        buildModel_plot_layout = function() private$..buildModel_plot_layout$value,
        buildModel_show_histo = function() private$..buildModel_show_histo$value,
        buildModel_show_frequencies = function() private$..buildModel_show_frequencies$value,
        buildModel_show_mosaic = function() private$..buildModel_show_mosaic$value,
        buildModel_digits = function() private$..buildModel_digits$value,
        centrality_loops = function() private$..centrality_loops$value,
        centrality_normalize = function() private$..centrality_normalize$value,
        centrality_show_table = function() private$..centrality_show_table$value,
        centrality_show_plot = function() private$..centrality_show_plot$value,
        centrality_Betweenness = function() private$..centrality_Betweenness$value,
        centrality_BetweennessRSP = function() private$..centrality_BetweennessRSP$value,
        centrality_Closeness = function() private$..centrality_Closeness$value,
        centrality_ClosenessIn = function() private$..centrality_ClosenessIn$value,
        centrality_ClosenessOut = function() private$..centrality_ClosenessOut$value,
        centrality_Clustering = function() private$..centrality_Clustering$value,
        centrality_Diffusion = function() private$..centrality_Diffusion$value,
        centrality_InStrength = function() private$..centrality_InStrength$value,
        centrality_OutStrength = function() private$..centrality_OutStrength$value,
        edgeBetweenness_show_table = function() private$..edgeBetweenness_show_table$value,
        edgeBetweenness_show_plot = function() private$..edgeBetweenness_show_plot$value,
        edgeBetweenness_plot_cut = function() private$..edgeBetweenness_plot_cut$value,
        edgeBetweenness_plot_min_value = function() private$..edgeBetweenness_plot_min_value$value,
        edgeBetweenness_plot_edge_label_size = function() private$..edgeBetweenness_plot_edge_label_size$value,
        edgeBetweenness_plot_node_size = function() private$..edgeBetweenness_plot_node_size$value,
        edgeBetweenness_plot_node_label_size = function() private$..edgeBetweenness_plot_node_label_size$value,
        edgeBetweenness_plot_layout = function() private$..edgeBetweenness_plot_layout$value,
        community_methods = function() private$..community_methods$value,
        community_gamma = function() private$..community_gamma$value,
        community_show_table = function() private$..community_show_table$value,
        community_show_plot = function() private$..community_show_plot$value,
        cliques_size = function() private$..cliques_size$value,
        cliques_threshold = function() private$..cliques_threshold$value,
        cliques_show_text = function() private$..cliques_show_text$value,
        cliques_show_plot = function() private$..cliques_show_plot$value,
        cliques_plot_cut = function() private$..cliques_plot_cut$value,
        cliques_plot_min_value = function() private$..cliques_plot_min_value$value,
        cliques_plot_edge_label_size = function() private$..cliques_plot_edge_label_size$value,
        cliques_plot_node_size = function() private$..cliques_plot_node_size$value,
        cliques_plot_node_label_size = function() private$..cliques_plot_node_label_size$value,
        cliques_plot_layout = function() private$..cliques_plot_layout$value,
        bootstrap_iteration = function() private$..bootstrap_iteration$value,
        bootstrap_level = function() private$..bootstrap_level$value,
        bootstrap_method = function() private$..bootstrap_method$value,
        bootstrap_range_low = function() private$..bootstrap_range_low$value,
        bootstrap_range_up = function() private$..bootstrap_range_up$value,
        bootstrap_threshold = function() private$..bootstrap_threshold$value,
        bootstrap_show_plot = function() private$..bootstrap_show_plot$value,
        bootstrap_show_table = function() private$..bootstrap_show_table$value,
        bootstrap_plot_cut = function() private$..bootstrap_plot_cut$value,
        bootstrap_plot_min_value = function() private$..bootstrap_plot_min_value$value,
        bootstrap_plot_edge_label_size = function() private$..bootstrap_plot_edge_label_size$value,
        bootstrap_plot_node_size = function() private$..bootstrap_plot_node_size$value,
        bootstrap_plot_node_label_size = function() private$..bootstrap_plot_node_label_size$value,
        bootstrap_plot_layout = function() private$..bootstrap_plot_layout$value,
        sequences_type = function() private$..sequences_type$value,
        sequences_scale = function() private$..sequences_scale$value,
        sequences_geom = function() private$..sequences_geom$value,
        sequences_include_na = function() private$..sequences_include_na$value,
        sequences_tick = function() private$..sequences_tick$value,
        sequences_show_plot = function() private$..sequences_show_plot$value),
    private = list(
        ..buildModel_variables_long_actor = NA,
        ..buildModel_variables_long_time = NA,
        ..buildModel_variables_long_action = NA,
        ..buildModel_variables_long_order = NA,
        ..buildModel_type = NA,
        ..buildModel_scaling = NA,
        ..buildModel_show_matrix = NA,
        ..buildModel_threshold = NA,
        ..buildModel_show_plot = NA,
        ..buildModel_plot_cut = NA,
        ..buildModel_plot_min_value = NA,
        ..buildModel_plot_edge_label_size = NA,
        ..buildModel_plot_node_size = NA,
        ..buildModel_plot_node_label_size = NA,
        ..buildModel_plot_layout = NA,
        ..buildModel_show_histo = NA,
        ..buildModel_show_frequencies = NA,
        ..buildModel_show_mosaic = NA,
        ..buildModel_digits = NA,
        ..centrality_loops = NA,
        ..centrality_normalize = NA,
        ..centrality_show_table = NA,
        ..centrality_show_plot = NA,
        ..centrality_Betweenness = NA,
        ..centrality_BetweennessRSP = NA,
        ..centrality_Closeness = NA,
        ..centrality_ClosenessIn = NA,
        ..centrality_ClosenessOut = NA,
        ..centrality_Clustering = NA,
        ..centrality_Diffusion = NA,
        ..centrality_InStrength = NA,
        ..centrality_OutStrength = NA,
        ..edgeBetweenness_show_table = NA,
        ..edgeBetweenness_show_plot = NA,
        ..edgeBetweenness_plot_cut = NA,
        ..edgeBetweenness_plot_min_value = NA,
        ..edgeBetweenness_plot_edge_label_size = NA,
        ..edgeBetweenness_plot_node_size = NA,
        ..edgeBetweenness_plot_node_label_size = NA,
        ..edgeBetweenness_plot_layout = NA,
        ..community_methods = NA,
        ..community_gamma = NA,
        ..community_show_table = NA,
        ..community_show_plot = NA,
        ..cliques_size = NA,
        ..cliques_threshold = NA,
        ..cliques_show_text = NA,
        ..cliques_show_plot = NA,
        ..cliques_plot_cut = NA,
        ..cliques_plot_min_value = NA,
        ..cliques_plot_edge_label_size = NA,
        ..cliques_plot_node_size = NA,
        ..cliques_plot_node_label_size = NA,
        ..cliques_plot_layout = NA,
        ..bootstrap_iteration = NA,
        ..bootstrap_level = NA,
        ..bootstrap_method = NA,
        ..bootstrap_range_low = NA,
        ..bootstrap_range_up = NA,
        ..bootstrap_threshold = NA,
        ..bootstrap_show_plot = NA,
        ..bootstrap_show_table = NA,
        ..bootstrap_plot_cut = NA,
        ..bootstrap_plot_min_value = NA,
        ..bootstrap_plot_edge_label_size = NA,
        ..bootstrap_plot_node_size = NA,
        ..bootstrap_plot_node_label_size = NA,
        ..bootstrap_plot_layout = NA,
        ..sequences_type = NA,
        ..sequences_scale = NA,
        ..sequences_geom = NA,
        ..sequences_include_na = NA,
        ..sequences_tick = NA,
        ..sequences_show_plot = NA)
)

TNAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "TNAResults",
    inherit = jmvcore::Group,
    active = list(
        errorText = function() private$.items[["errorText"]],
        tnaTitle = function() private$.items[["tnaTitle"]],
        buildModelTitle = function() private$.items[["buildModelTitle"]],
        buildModelContent = function() private$.items[["buildModelContent"]],
        buildModel_plot = function() private$.items[["buildModel_plot"]],
        buildModel_histo = function() private$.items[["buildModel_histo"]],
        buildModel_frequencies = function() private$.items[["buildModel_frequencies"]],
        buildModel_mosaic = function() private$.items[["buildModel_mosaic"]],
        centralityTitle = function() private$.items[["centralityTitle"]],
        centralityContent = function() private$.items[["centralityContent"]],
        centralityTable = function() private$.items[["centralityTable"]],
        centrality_plot = function() private$.items[["centrality_plot"]],
        edgeBetweennessTitle = function() private$.items[["edgeBetweennessTitle"]],
        edgeBetweenness_plot = function() private$.items[["edgeBetweenness_plot"]],
        edgeBetweennessTable = function() private$.items[["edgeBetweennessTable"]],
        edgeBetweennessNoResultsNote = function() private$.items[["edgeBetweennessNoResultsNote"]],
        communityTitle = function() private$.items[["communityTitle"]],
        communityContent = function() private$.items[["communityContent"]],
        community_plot = function() private$.items[["community_plot"]],
        communityTable = function() private$.items[["communityTable"]],
        cliquesTitle = function() private$.items[["cliquesTitle"]],
        cliquesContent = function() private$.items[["cliquesContent"]],
        cliques_multiple_plot = function() private$.items[["cliques_multiple_plot"]],
        bootstrapTitle = function() private$.items[["bootstrapTitle"]],
        bootstrap_plot = function() private$.items[["bootstrap_plot"]],
        bootstrapTable = function() private$.items[["bootstrapTable"]],
        permutationTable = function() private$.items[["permutationTable"]],
        sequences_plot = function() private$.items[["sequences_plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Transition Network Analysis",
                refs=list(
                    "TNA"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="errorText",
                title="Error",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="tnaTitle",
                title="TNA",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="buildModelTitle",
                title="Model",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="buildModelContent",
                visible=FALSE,
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold")))
            self$add(jmvcore::Image$new(
                options=options,
                name="buildModel_plot",
                width=600,
                height=600,
                visible=FALSE,
                renderFun=".showBuildModelPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "buildModel_plot_cut",
                    "buildModel_plot_min_value",
                    "buildModel_plot_edge_label_size",
                    "buildModel_plot_node_size",
                    "buildModel_plot_node_label_size",
                    "buildModel_plot_layout")))
            self$add(jmvcore::Image$new(
                options=options,
                name="buildModel_histo",
                width=600,
                height=600,
                visible=FALSE,
                renderFun=".showBuildModelHisto",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold")))
            self$add(jmvcore::Image$new(
                options=options,
                name="buildModel_frequencies",
                width=600,
                height=600,
                visible=FALSE,
                renderFun=".showBuildModelFrequencies",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold")))
            self$add(jmvcore::Image$new(
                options=options,
                name="buildModel_mosaic",
                width=400,
                height=300,
                visible=FALSE,
                renderFun=".showBuildModelMosaic",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "buildModel_digits")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="centralityTitle",
                title="Centrality",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="centralityContent",
                visible=FALSE,
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "centrality_loops",
                    "centrality_normalize",
                    "centrality_Betweenness",
                    "centrality_BetweennessRSP",
                    "centrality_Closeness",
                    "centrality_ClosenessIn",
                    "centrality_ClosenessOut",
                    "centrality_Clustering",
                    "centrality_Diffusion",
                    "centrality_InStrength",
                    "centrality_OutStrength")))
            self$add(jmvcore::Table$new(
                options=options,
                name="centralityTable",
                title="Centrality Measures",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="state", 
                        `type`="text")),
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "centrality_loops",
                    "centrality_normalize",
                    "centrality_Betweenness",
                    "centrality_BetweennessRSP",
                    "centrality_Closeness",
                    "centrality_ClosenessIn",
                    "centrality_ClosenessOut",
                    "centrality_Clustering",
                    "centrality_Diffusion",
                    "centrality_InStrength",
                    "centrality_OutStrength")))
            self$add(jmvcore::Image$new(
                options=options,
                name="centrality_plot",
                width=600,
                height=600,
                visible=FALSE,
                renderFun=".showCentralityPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "centrality_loops",
                    "centrality_normalize",
                    "centrality_Betweenness",
                    "centrality_BetweennessRSP",
                    "centrality_Closeness",
                    "centrality_ClosenessIn",
                    "centrality_ClosenessOut",
                    "centrality_Clustering",
                    "centrality_Diffusion",
                    "centrality_InStrength",
                    "centrality_OutStrength")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="edgeBetweennessTitle",
                title="Edge betweenness",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="edgeBetweenness_plot",
                width=600,
                height=600,
                visible=FALSE,
                renderFun=".showEdgeBetweennessPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "edgeBetweenness_plot_cut",
                    "edgeBetweenness_plot_min_value",
                    "edgeBetweenness_plot_edge_label_size",
                    "edgeBetweenness_plot_node_size",
                    "edgeBetweenness_plot_node_label_size",
                    "edgeBetweenness_plot_layout")))
            self$add(jmvcore::Table$new(
                options=options,
                name="edgeBetweennessTable",
                title="Edge Betweenness",
                visible="(edgeBetweenness_show_table)",
                columns=list(
                    list(
                        `name`="from", 
                        `title`="From", 
                        `type`="text"),
                    list(
                        `name`="to", 
                        `title`="To", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number")),
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="edgeBetweennessNoResultsNote",
                visible=FALSE,
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="communityTitle",
                title="Community",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="communityContent",
                visible=FALSE,
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "community_methods",
                    "community_gamma")))
            self$add(jmvcore::Image$new(
                options=options,
                name="community_plot",
                width=600,
                height=600,
                visible=FALSE,
                renderFun=".showCommunityPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "community_methods",
                    "community_gamma")))
            self$add(jmvcore::Table$new(
                options=options,
                name="communityTable",
                title="Community Assignments",
                visible="(community_show_table)",
                columns=list(
                    list(
                        `name`="state", 
                        `title`="State", 
                        `type`="text")),
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "community_methods",
                    "community_gamma")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cliquesTitle",
                title="Cliques",
                visible=FALSE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="cliquesContent",
                visible=FALSE,
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "cliques_size",
                    "cliques_threshold")))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    cliques_plot1 = function() private$.items[["cliques_plot1"]],
                    cliques_plot2 = function() private$.items[["cliques_plot2"]],
                    cliques_plot3 = function() private$.items[["cliques_plot3"]],
                    cliques_plot4 = function() private$.items[["cliques_plot4"]],
                    cliques_plot5 = function() private$.items[["cliques_plot5"]],
                    cliques_plot6 = function() private$.items[["cliques_plot6"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="cliques_multiple_plot",
                            title="",
                            clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "cliques_size",
                    "cliques_threshold",
                    "cliques_plot_min_value",
                    "cliques_plot_edge_label_size",
                    "cliques_plot_node_size",
                    "cliques_plot_node_label_size",
                    "cliques_plot_layout"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot1",
                            width=600,
                            height=600,
                            visible=TRUE,
                            renderFun=".showCliquesPlot1"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot2",
                            width=600,
                            height=600,
                            visible=TRUE,
                            renderFun=".showCliquesPlot2"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot3",
                            width=600,
                            height=600,
                            visible=TRUE,
                            renderFun=".showCliquesPlot3"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot4",
                            width=600,
                            height=600,
                            visible=TRUE,
                            renderFun=".showCliquesPlot4"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot5",
                            width=600,
                            height=600,
                            visible=TRUE,
                            renderFun=".showCliquesPlot5"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="cliques_plot6",
                            width=600,
                            height=600,
                            visible=TRUE,
                            renderFun=".showCliquesPlot6"))}))$new(options=options))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="bootstrapTitle",
                title="Bootstrap",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="bootstrap_plot",
                width=600,
                height=600,
                visible=FALSE,
                renderFun=".showBootstrapPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "bootstrap_iteration",
                    "bootstrap_level",
                    "bootstrap_method",
                    "bootstrap_range_low",
                    "bootstrap_range_up",
                    "bootstrap_threshold",
                    "bootstrap_plot_cut",
                    "bootstrap_plot_min_value",
                    "bootstrap_plot_edge_label_size",
                    "bootstrap_plot_node_size",
                    "bootstrap_plot_node_label_size",
                    "bootstrap_plot_layout")))
            self$add(jmvcore::Table$new(
                options=options,
                name="bootstrapTable",
                title="Bootstrap Results",
                visible="(bootstrap_show_table)",
                columns=list(
                    list(
                        `name`="from", 
                        `title`="From", 
                        `type`="text"),
                    list(
                        `name`="to", 
                        `title`="To", 
                        `type`="text"),
                    list(
                        `name`="weight", 
                        `title`="Weight", 
                        `type`="number"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number"),
                    list(
                        `name`="cr_lower", 
                        `title`="CR Lower", 
                        `type`="number"),
                    list(
                        `name`="cr_upper", 
                        `title`="CR Upper", 
                        `type`="number"),
                    list(
                        `name`="ci_lower", 
                        `title`="CI Lower", 
                        `type`="number"),
                    list(
                        `name`="ci_upper", 
                        `title`="CI Upper", 
                        `type`="number"),
                    list(
                        `name`="significant", 
                        `title`="Significant", 
                        `type`="text")),
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "bootstrap_iteration",
                    "bootstrap_level",
                    "bootstrap_method",
                    "bootstrap_range_low",
                    "bootstrap_range_up",
                    "bootstrap_threshold")))
            self$add(jmvcore::Table$new(
                options=options,
                name="permutationTable",
                title="Permutation Test Results",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="group_comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="edge_name", 
                        `title`="Edge", 
                        `type`="text"),
                    list(
                        `name`="diff_true", 
                        `title`="Diff (True)", 
                        `type`="number"),
                    list(
                        `name`="effect_size", 
                        `title`="Effect Size", 
                        `type`="number"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number")),
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "permutation_iter",
                    "permutation_paired",
                    "permutation_level")))
            self$add(jmvcore::Image$new(
                options=options,
                name="sequences_plot",
                title="Sequence Analysis Plot",
                width=600,
                height=600,
                visible=FALSE,
                renderFun=".showSequencesPlot",
                clearWith=list(
                    "buildModel_variables_long_actor",
                    "buildModel_variables_long_time",
                    "buildModel_variables_long_action",
                    "buildModel_variables_long_order",
                    "buildModel_type",
                    "buildModel_scaling",
                    "buildModel_threshold",
                    "sequences_type",
                    "sequences_scale",
                    "sequences_geom",
                    "sequences_include_na",
                    "sequences_tick")))}))

TNABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "TNABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "JTNA",
                name = "TNA",
                version = c(1,4,0),
                options = options,
                results = TNAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Transition Network Analysis
#'
#' 
#' @param data .
#' @param buildModel_variables_long_actor .
#' @param buildModel_variables_long_time .
#' @param buildModel_variables_long_action .
#' @param buildModel_variables_long_order .
#' @param buildModel_type .
#' @param buildModel_scaling .
#' @param buildModel_show_matrix .
#' @param buildModel_threshold .
#' @param buildModel_show_plot .
#' @param buildModel_plot_cut .
#' @param buildModel_plot_min_value .
#' @param buildModel_plot_edge_label_size .
#' @param buildModel_plot_node_size .
#' @param buildModel_plot_node_label_size .
#' @param buildModel_plot_layout .
#' @param buildModel_show_histo .
#' @param buildModel_show_frequencies .
#' @param buildModel_show_mosaic .
#' @param buildModel_digits .
#' @param centrality_loops .
#' @param centrality_normalize .
#' @param centrality_show_table .
#' @param centrality_show_plot .
#' @param centrality_Betweenness .
#' @param centrality_BetweennessRSP .
#' @param centrality_Closeness .
#' @param centrality_ClosenessIn .
#' @param centrality_ClosenessOut .
#' @param centrality_Clustering .
#' @param centrality_Diffusion .
#' @param centrality_InStrength .
#' @param centrality_OutStrength .
#' @param edgeBetweenness_show_table .
#' @param edgeBetweenness_show_plot .
#' @param edgeBetweenness_plot_cut .
#' @param edgeBetweenness_plot_min_value .
#' @param edgeBetweenness_plot_edge_label_size .
#' @param edgeBetweenness_plot_node_size .
#' @param edgeBetweenness_plot_node_label_size .
#' @param edgeBetweenness_plot_layout .
#' @param community_methods .
#' @param community_gamma .
#' @param community_show_table .
#' @param community_show_plot .
#' @param cliques_size .
#' @param cliques_threshold .
#' @param cliques_show_text .
#' @param cliques_show_plot .
#' @param cliques_plot_cut .
#' @param cliques_plot_min_value .
#' @param cliques_plot_edge_label_size .
#' @param cliques_plot_node_size .
#' @param cliques_plot_node_label_size .
#' @param cliques_plot_layout .
#' @param bootstrap_iteration .
#' @param bootstrap_level .
#' @param bootstrap_method .
#' @param bootstrap_range_low .
#' @param bootstrap_range_up .
#' @param bootstrap_threshold .
#' @param bootstrap_show_plot .
#' @param bootstrap_show_table .
#' @param bootstrap_plot_cut .
#' @param bootstrap_plot_min_value .
#' @param bootstrap_plot_edge_label_size .
#' @param bootstrap_plot_node_size .
#' @param bootstrap_plot_node_label_size .
#' @param bootstrap_plot_layout .
#' @param sequences_type .
#' @param sequences_scale .
#' @param sequences_geom .
#' @param sequences_include_na .
#' @param sequences_tick .
#' @param sequences_show_plot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$errorText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$tnaTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$buildModelTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$buildModelContent} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$buildModel_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$buildModel_histo} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$buildModel_frequencies} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$buildModel_mosaic} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$centralityTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$centralityContent} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$centralityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$centrality_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$edgeBetweennessTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$edgeBetweenness_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$edgeBetweennessTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$edgeBetweennessNoResultsNote} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$communityTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$communityContent} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$community_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$communityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cliquesTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cliquesContent} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cliques_multiple_plot$cliques_plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cliques_multiple_plot$cliques_plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cliques_multiple_plot$cliques_plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cliques_multiple_plot$cliques_plot4} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cliques_multiple_plot$cliques_plot5} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cliques_multiple_plot$cliques_plot6} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$bootstrapTitle} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$bootstrap_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$bootstrapTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$permutationTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sequences_plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$centralityTable$asDF}
#'
#' \code{as.data.frame(results$centralityTable)}
#'
#' @export
TNA <- function(
    data,
    buildModel_variables_long_actor,
    buildModel_variables_long_time,
    buildModel_variables_long_action,
    buildModel_variables_long_order,
    buildModel_type = "relative",
    buildModel_scaling = "noScaling",
    buildModel_show_matrix = FALSE,
    buildModel_threshold = 900,
    buildModel_show_plot = TRUE,
    buildModel_plot_cut = 0.1,
    buildModel_plot_min_value = 0.05,
    buildModel_plot_edge_label_size = 1,
    buildModel_plot_node_size = 1,
    buildModel_plot_node_label_size = 1,
    buildModel_plot_layout,
    buildModel_show_histo = FALSE,
    buildModel_show_frequencies = FALSE,
    buildModel_show_mosaic = FALSE,
    buildModel_digits = 1,
    centrality_loops = FALSE,
    centrality_normalize = FALSE,
    centrality_show_table = FALSE,
    centrality_show_plot = FALSE,
    centrality_Betweenness = TRUE,
    centrality_BetweennessRSP = FALSE,
    centrality_Closeness = FALSE,
    centrality_ClosenessIn = FALSE,
    centrality_ClosenessOut = FALSE,
    centrality_Clustering = FALSE,
    centrality_Diffusion = FALSE,
    centrality_InStrength = TRUE,
    centrality_OutStrength = TRUE,
    edgeBetweenness_show_table = FALSE,
    edgeBetweenness_show_plot = FALSE,
    edgeBetweenness_plot_cut = 0.1,
    edgeBetweenness_plot_min_value = 0.05,
    edgeBetweenness_plot_edge_label_size = 1,
    edgeBetweenness_plot_node_size = 1,
    edgeBetweenness_plot_node_label_size = 1,
    edgeBetweenness_plot_layout,
    community_methods = "spinglass",
    community_gamma = 1,
    community_show_table = FALSE,
    community_show_plot = FALSE,
    cliques_size = 2,
    cliques_threshold = 0,
    cliques_show_text = FALSE,
    cliques_show_plot = FALSE,
    cliques_plot_cut = 0.1,
    cliques_plot_min_value = 0,
    cliques_plot_edge_label_size = 1,
    cliques_plot_node_size = 1,
    cliques_plot_node_label_size = 1,
    cliques_plot_layout = "circle",
    bootstrap_iteration = 1000,
    bootstrap_level = 0.05,
    bootstrap_method = "stability",
    bootstrap_range_low = 0.75,
    bootstrap_range_up = 1.25,
    bootstrap_threshold = 0.1,
    bootstrap_show_plot = FALSE,
    bootstrap_show_table = FALSE,
    bootstrap_plot_cut = 0.1,
    bootstrap_plot_min_value = 0.05,
    bootstrap_plot_edge_label_size = 1,
    bootstrap_plot_node_size = 1,
    bootstrap_plot_node_label_size = 1,
    bootstrap_plot_layout,
    sequences_type = "index",
    sequences_scale = "proportion",
    sequences_geom = "bar",
    sequences_include_na = TRUE,
    sequences_tick = 5,
    sequences_show_plot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("TNA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(buildModel_variables_long_actor)) buildModel_variables_long_actor <- jmvcore::resolveQuo(jmvcore::enquo(buildModel_variables_long_actor))
    if ( ! missing(buildModel_variables_long_time)) buildModel_variables_long_time <- jmvcore::resolveQuo(jmvcore::enquo(buildModel_variables_long_time))
    if ( ! missing(buildModel_variables_long_action)) buildModel_variables_long_action <- jmvcore::resolveQuo(jmvcore::enquo(buildModel_variables_long_action))
    if ( ! missing(buildModel_variables_long_order)) buildModel_variables_long_order <- jmvcore::resolveQuo(jmvcore::enquo(buildModel_variables_long_order))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(buildModel_variables_long_actor), buildModel_variables_long_actor, NULL),
            `if`( ! missing(buildModel_variables_long_time), buildModel_variables_long_time, NULL),
            `if`( ! missing(buildModel_variables_long_action), buildModel_variables_long_action, NULL),
            `if`( ! missing(buildModel_variables_long_order), buildModel_variables_long_order, NULL))


    options <- TNAOptions$new(
        buildModel_variables_long_actor = buildModel_variables_long_actor,
        buildModel_variables_long_time = buildModel_variables_long_time,
        buildModel_variables_long_action = buildModel_variables_long_action,
        buildModel_variables_long_order = buildModel_variables_long_order,
        buildModel_type = buildModel_type,
        buildModel_scaling = buildModel_scaling,
        buildModel_show_matrix = buildModel_show_matrix,
        buildModel_threshold = buildModel_threshold,
        buildModel_show_plot = buildModel_show_plot,
        buildModel_plot_cut = buildModel_plot_cut,
        buildModel_plot_min_value = buildModel_plot_min_value,
        buildModel_plot_edge_label_size = buildModel_plot_edge_label_size,
        buildModel_plot_node_size = buildModel_plot_node_size,
        buildModel_plot_node_label_size = buildModel_plot_node_label_size,
        buildModel_plot_layout = buildModel_plot_layout,
        buildModel_show_histo = buildModel_show_histo,
        buildModel_show_frequencies = buildModel_show_frequencies,
        buildModel_show_mosaic = buildModel_show_mosaic,
        buildModel_digits = buildModel_digits,
        centrality_loops = centrality_loops,
        centrality_normalize = centrality_normalize,
        centrality_show_table = centrality_show_table,
        centrality_show_plot = centrality_show_plot,
        centrality_Betweenness = centrality_Betweenness,
        centrality_BetweennessRSP = centrality_BetweennessRSP,
        centrality_Closeness = centrality_Closeness,
        centrality_ClosenessIn = centrality_ClosenessIn,
        centrality_ClosenessOut = centrality_ClosenessOut,
        centrality_Clustering = centrality_Clustering,
        centrality_Diffusion = centrality_Diffusion,
        centrality_InStrength = centrality_InStrength,
        centrality_OutStrength = centrality_OutStrength,
        edgeBetweenness_show_table = edgeBetweenness_show_table,
        edgeBetweenness_show_plot = edgeBetweenness_show_plot,
        edgeBetweenness_plot_cut = edgeBetweenness_plot_cut,
        edgeBetweenness_plot_min_value = edgeBetweenness_plot_min_value,
        edgeBetweenness_plot_edge_label_size = edgeBetweenness_plot_edge_label_size,
        edgeBetweenness_plot_node_size = edgeBetweenness_plot_node_size,
        edgeBetweenness_plot_node_label_size = edgeBetweenness_plot_node_label_size,
        edgeBetweenness_plot_layout = edgeBetweenness_plot_layout,
        community_methods = community_methods,
        community_gamma = community_gamma,
        community_show_table = community_show_table,
        community_show_plot = community_show_plot,
        cliques_size = cliques_size,
        cliques_threshold = cliques_threshold,
        cliques_show_text = cliques_show_text,
        cliques_show_plot = cliques_show_plot,
        cliques_plot_cut = cliques_plot_cut,
        cliques_plot_min_value = cliques_plot_min_value,
        cliques_plot_edge_label_size = cliques_plot_edge_label_size,
        cliques_plot_node_size = cliques_plot_node_size,
        cliques_plot_node_label_size = cliques_plot_node_label_size,
        cliques_plot_layout = cliques_plot_layout,
        bootstrap_iteration = bootstrap_iteration,
        bootstrap_level = bootstrap_level,
        bootstrap_method = bootstrap_method,
        bootstrap_range_low = bootstrap_range_low,
        bootstrap_range_up = bootstrap_range_up,
        bootstrap_threshold = bootstrap_threshold,
        bootstrap_show_plot = bootstrap_show_plot,
        bootstrap_show_table = bootstrap_show_table,
        bootstrap_plot_cut = bootstrap_plot_cut,
        bootstrap_plot_min_value = bootstrap_plot_min_value,
        bootstrap_plot_edge_label_size = bootstrap_plot_edge_label_size,
        bootstrap_plot_node_size = bootstrap_plot_node_size,
        bootstrap_plot_node_label_size = bootstrap_plot_node_label_size,
        bootstrap_plot_layout = bootstrap_plot_layout,
        sequences_type = sequences_type,
        sequences_scale = sequences_scale,
        sequences_geom = sequences_geom,
        sequences_include_na = sequences_include_na,
        sequences_tick = sequences_tick,
        sequences_show_plot = sequences_show_plot)

    analysis <- TNAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

